### ISSUE TITLE
unable to retrieve Resource

### ISSUE THREAD

**Issue by PhE** [thecodingmachine/gotenberg#263]
I encounter this error while trying to support SVG inkscape convert :
```
context.Context.MustResource: unable to retrieve the resource.Resource from our custom context.Context
```

Here is the output with LOG_LEVEL=DEBUG :
```
$ make gotenberg
docker run -it --rm -e MAXIMUM_WAIT_TIMEOUT=30.0 -e MAXIMUM_WAIT_DELAY=10.0 -e MAXIMUM_WEBHOOK_URL_TIMEOUT=30.0 -e DEFAULT_WEBHOOK_URL_TIMEOUT=10.0 -e MAXIMUM_WEBHOOK_URL_TIMEOUT=30.0 -e DEFAULT_LISTEN_PORT=3000 -e DISABLE_GOOGLE_CHROME=0 -e DISABLE_UNOCONV=0 -e LOG_LEVEL=DEBUG -e ROOT_PATH=/ -e DEFAULT_GOOGLE_CHROME_RPCC_BUFFER_SIZE=1048576  -p "3000:3000" thecodingmachine/gotenberg:snapshot
INFO[0000] Gotenberg snapshot                            op=main trace=system
DEBU[0000] configuration: {maximumWaitTimeout:30 maximumWaitDelay:10 maximumWebhookURLTimeout:30 defaultWaitTimeout:10 defaultWebhookURLTimeout:10 defaultListenPort:3000 disableGoogleChrome:false disableInkscape:false disableUnoconv:false logLevel:DEBUG rootPath:/ maximumGoogleChromeRpccBufferSize:104857600 defaultGoogleChromeRpccBufferSize:1048576}  op=main trace=system
DEBU[0000] starting new Google Chrome headless process on port 9222...  op=chrome.Start trace=system
DEBU[0000] executing command: google-chrome-stable --no-sandbox --headless --disable-dev-shm-usage --font-render-hinting=none --remote-debugging-port=9222 --disable-gpu --disable-translate --disable-extensions --disable-background-networking --safebrowsing-disable-auto-update --disable-sync --disable-default-apps --hide-scrollbars --metrics-recording-only --mute-audio --no-first-run  op=xexec.LogBeforeExecute trace=system
DEBU[0000] waiting '500ms' for allowing Google Chrome to warmup  op=chrome.warmup trace=system
DEBU[0000] [1130/074504.561227:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory  op="stderr.google-chrome-stable.--no-sandbox.--headless.--disable-dev-shm-usage.--font-render-hinting=none.--remote-debugging-port=9222.--disable-gpu.--disable-translate.--disable-extensions.--disable-background-networking.--safebrowsing-disable-auto-update.--disable-sync.--disable-default-apps.--hide-scrollbars.--metrics-recording-only.--mute-audio.--no-first-run" trace=system
DEBU[0000] DevTools listening on ws://127.0.0.1:9222/devtools/browser/ca29b656-aa2f-4319-8557-3e0dd7251fca  op="stderr.google-chrome-stable.--no-sandbox.--headless.--disable-dev-shm-usage.--font-render-hinting=none.--remote-debugging-port=9222.--disable-gpu.--disable-translate.--disable-extensions.--disable-background-networking.--safebrowsing-disable-auto-update.--disable-sync.--disable-default-apps.--hide-scrollbars.--metrics-recording-only.--mute-audio.--no-first-run" trace=system
DEBU[0000] checking Google Chrome headless process viability via endpoint 'http://localhost:9222/json/version'  op=chrome.isViable trace=system
DEBU[0000] Google Chrome headless is viable as endpoint returned '&{HeadlessChrome/87.0.4280.66 1.3 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.66 Safari/537.36 8.7.220.25 537.36 (@fd98a29dd59b36f71e4741332c9ad5bda42094bf)  ws://localhost:9222/devtools/browser/ca29b656-aa2f-4319-8557-3e0dd7251fca}'  op=chrome.isViable trace=system
INFO[0000] http server started on port '3000'            op=main trace=system
DEBU[0013] handling inkscape request...                  op=xhttp.inkscapeHandler trace=6a28XT3Y7meKpDdXfrdz1QP3FwRuwyoG
DEBU[0013] xxxxxxxxxxxx dbg 0                            op=xhttp.inkscapeHandler trace=6a28XT3Y7meKpDdXfrdz1QP3FwRuwyoG
echo: http: panic serving 172.17.0.1:37658: context.Context.MustResource: unable to retrieve the resource.Resource from our custom context.Context
goroutine 14 [running]:
net/http.(*conn).serve.func1(0xc0001af2c0)
	/usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x994120, 0xc00020a8f0)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/thecodingmachine/gotenberg/internal/app/xhttp/pkg/context.Context.MustResource(0xb8d7e0, 0xc0001af360, 0xc000205730, 0xaaf011, 0x5, 0x403e000000000000, 0x4024000000000000, 0x403e000000000000, 0x4024000000000000, 0x4024000000000000, ...)
	/gotenberg/package/internal/app/xhttp/pkg/context/context.go:139 +0x1e3
github.com/thecodingmachine/gotenberg/internal/app/xhttp.inkscapeHandler.func1(0xc00008e698, 0x413953)
	/gotenberg/package/internal/app/xhttp/handler.go:116 +0x237
github.com/thecodingmachine/gotenberg/internal/app/xhttp.inkscapeHandler(0xb8d9c0, 0xc0000205a0, 0xc00008e9d8, 0xc0000205a0)
	/gotenberg/package/internal/app/xhttp/handler.go:134 +0x5e
github.com/labstack/echo/v4.(*Echo).add.func1(0xb8d9c0, 0xc0000205a0, 0xb8d9c0, 0xc0000205a0)
	/gotenberg/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/echo.go:512 +0x8a
github.com/thecodingmachine/gotenberg/internal/app/xhttp.errorMiddleware.func1.1(0xb8d9c0, 0xc0000204b0, 0x20, 0x20)
	/gotenberg/package/internal/app/xhttp/middleware.go:93 +0x1ec
github.com/thecodingmachine/gotenberg/internal/app/xhttp.cleanupMiddleware.func1.1(0xb8d9c0, 0xc0000204b0, 0xb8d9c0, 0xc0000204b0)
	/gotenberg/package/internal/app/xhttp/middleware.go:81 +0x54
github.com/thecodingmachine/gotenberg/internal/app/xhttp.loggerMiddleware.func1.1(0xb8d9c0, 0xc0000203c0, 0xb8d9c0, 0xc0000203c0)
	/gotenberg/package/internal/app/xhttp/middleware.go:67 +0x1f4
github.com/thecodingmachine/gotenberg/internal/app/xhttp.contextMiddleware.func1.1(0xb8d7e0, 0xc0001af360, 0x4, 0x4)
	/gotenberg/package/internal/app/xhttp/middleware.go:37 +0xc58
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0000d8000, 0xb7cc00, 0xc00024c000, 0xc000154600)
	/gotenberg/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/echo.go:623 +0x16c
net/http.serverHandler.ServeHTTP(0xc0000d2000, 0xb7cc00, 0xc00024c000, 0xc000154600)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0001af2c0, 0xb7de00, 0xc00002b1c0)
	/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c
```

The forked source is [here](https://github.com/PhE/gotenberg/tree/openapi).

The command to reproduce :
```
cd test/testdata/svg
curl --request POST \
    --url http://localhost:3000/convert/inkscape \
    --header 'Content-Type: multipart/form-data' \
    --form files=@gotenberg.svg \
    -o result.pdf
```

Some help will be appreciated because I'm a total Go noob :wink:

**Comment by PhE** [comment]
I fixed it !
The SVG file uploaded where not added to the `multipartFormDataEndpoints` :

```go
func isMultipartFormDataEndpoint(config conf.Config, path string) bool {
	var multipartFormDataEndpoints []string
	multipartFormDataEndpoints = append(multipartFormDataEndpoints, mergeEndpoint(config))
	multipartFormDataEndpoints = append(multipartFormDataEndpoints, inkscapeEndpoint(config))  // <<<<
	if !config.DisableGoogleChrome() {
		multipartFormDataEndpoints = append(
			multipartFormDataEndpoints,
			htmlEndpoint(config),
			urlEndpoint(config),
			markdownEndpoint(config),
		)
	}
	if !config.DisableUnoconv() {
		multipartFormDataEndpoints = append(
			multipartFormDataEndpoints,
			officeEndpoint(config),
		)
	}
	for _, endpoint := range multipartFormDataEndpoints {
		if endpoint == path {
			return true
		}
	}
	return false
}
```
